### PR TITLE
Add option to use path style for S3.

### LINKED ISSUE #57: Allow PathStyle for S3
Using minio as an S3 provider, the connection to the bucket fails, because the PathStyle cannot be set to true.

Using the direct IP of my minio instance, BackWPup tries this:
`http://bucket.1.2.3.4`
instead of this:
`http://1.2.3.4/bucket`

Would be nice to have this as an option 👍

### PR DESCRIPTION
**Pull request by noplanman**
This PR adds a checkbox to allow the use of S3 instances which require a path style instead of subdomain style.

This is required for [Minio](https://minio.io), for example.

Fixes #57

### CODE REVIEW

**Comment by noplanman** [comment]
Arguably, a better solution would be to use an up-to-date version of the [AWS SDK package](https://packagist.org/packages/aws/aws-sdk-php).

Then it would be much easier to just add the `use_path_style_endpoint` parameter to the [S3 client constructor](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct).

**Comment by widoz** [comment]
Hi @noplanman Thanks for the pull request, I had a problem to import the patch in the latest version (3.6.7), could you make the branch align the branch to the master?

**Comment by noplanman** [comment]
@widoz Ok, should work now :+1:

**Comment by danielhuesken** [comment]
Will be added in a other way with other things.

**Pull request closed without merging**
