### PR TITLE
more translations

### PR DESCRIPTION
**Pull request by matheuswd**

### CODE REVIEW

**Comment by danielhuesken** [comment]
For translation you can use http://translate.marketpress.com/ register on http://translate.marketpress.com/sign-up/

**Comment by pedro-mendonca** [comment]
Hi @danielhuesken 
I'm doing a new translation for BackWPup also, it does not exist in http://translate.marketpress.com/
As I'm doing it with Poedit, maybe I can first make a PR here in GitHub before going to the translate site, it's easier to start than rewrite it all over again in the site.
Does Glotpress allow .po files upload?

**Comment by danielhuesken** [comment]
Hello, yes GlotPress allows .po files to upload. Give me the locale that you need and i will create it.

WordPress.org allows now translations for BAckWPup too. https://translate.wordpress.org/projects/wp-plugins/backwpup/dev

**Comment by pedro-mendonca** [comment]
I've already registered a few minutes ago, and included the pt_PT (Portuguese european) locale on the language.

**Comment by pedro-mendonca** [comment]
I didn't knew that WordPress plugins translation where already online. Still, on WordPress I can't upload any .po as far as I can see. What would be the best workflow for translating this plugin? WordPress site or translate.marketpress?

**Comment by danielhuesken** [comment]
The problem in moment is the PRO version on Marketpress all strings including the pro avale.
On wp.org i thnk that are only the free strings. 
In moment the best for us is the translation on Marketpress and we will add them to BackWPup. In future will can hopfuly improve this.

**Comment by pedro-mendonca** [comment]
ok, I'll keep using translate.marketpress, but how can I upload a .po file there to avoid pasting it string by string?

**Comment by pedro-mendonca** [comment]
Would you mind if I make a first PR here at github and than keep updating via translate.marketpress?

**Comment by danielhuesken** [comment]
Send the files to me with mail. I will add them for the moment.

**Comment by danielhuesken** [comment]
Can you check if you have on bozzom of the page a import link. http://translate.marketpress.com/projects/plugins/backwpup-pro/pt/default

**Comment by pedro-mendonca** [comment]
Yep, I do have now! :+1:

**Comment by pedro-mendonca** [comment]
I have a .po file fully updated with sources with just 885 strings, but the .pot and glotpress have 1174.
Is glotpress synced with current code?

**Comment by danielhuesken** [comment]
Yes with the Pro version. The Pro version hase some more strings. but we can use the same translation files for free and pro

**Comment by pedro-mendonca** [comment]
Ok, I'll update the .po with the current .pot.
Thanks :)

**Comment by pedro-mendonca** [comment]
Hi @danielhuesken 

I'm almost finishing the free version translation, missing just 5 strings on translate.wordpress.org.
I have some doubts on a few strings that you might explain to me.

What is this? "Empty output on working" 
I didn't understand even with the explanations in "Enable an empty Output on backup working." and "This do an empty output on job working. This can help in some situations or can brake the working. You must test it."

Another that I don't understand the context is "Start for table backup is not correctly set: %1$s " and "Length for table backup is not correctly set: %1$s ".

Some strings that I believe would need a cleanup because they're hard to read:
"WP Export file can not checked, because no XML extension loaded with the file can checked."
"Is your blog protected with HTTP basic authentication (.htaccess)? Or did you use a Plugin to secure wp-cron.php than use the authentication methods below"

Thanks.

**Comment by danielhuesken** [comment]
Can you give mir your wordpress.org account. Than i can let add you as Translation Editor.

"Empty output on working" is a spcial stting that produces an output with a spaces while a job running. In some cases it prevents job aborts.

The next strings are DB Table backup related and will only displayed on errors.

For the rest fell free to commit a better text ;)

**Comment by pedro-mendonca** [comment]
Hi,
Thank you, I'm already a Translation Editor (https://profiles.wordpress.org/pedromendonca/) and I've been pushing the translation of BackWPup also on wordpress https://translate.wordpress.org/locale/pt/default/wp-plugins/backwpup, and as there are only 5 strings left, I really want to translate it so people can get the translation automatically, I believe this only happens when it gets to 100% transtated.

About the "Empty output on working", when you say spaces, do you mean small amounts of time in between? or spaces in the outputed report text? Still don't quite understand it to translate it.

About the DB Table backup related strings, what are "Start" and "Lenght" of the tables? I've googled around on mysql properties but didn't found anything conclusive.

About the strings cleanup, before pushing I would like to confirm if the meaning is correct.
Are they correct like this?

"WP Export file can not checked, because no XML extension loaded with the file can checked."
"WP Export file can not **be** checked, because no XML extension **is** loaded, **to ensure the file verification**."

"Is your blog protected with HTTP basic authentication (.htaccess)? Or did you use a Plugin to secure wp-cron.php than use the authentication methods below"
"**If you protected your blog** with HTTP basic authentication (.htaccess)**, or you use** a Plugin to secure wp-cron.php**,** than use the authentication methods below**.**"

**Comment by danielhuesken** [comment]
Hello,

yes, only 100% translated will be delivered.

"Empty output on working": Its not easy to explain! With that option on backup process will be every secound some spaces send to the "Browser" that can prevent aborts of the backup script. Also on some hoster it can produce aborts.

 "Start" and "Lenght" are internal pointers, BackWPup looks how many rows in a table an save the position it is working on.

Yes, both correct. But i will impliment tham with an later update.

**Comment by pedro-mendonca** [comment]
Ok, thanks.
I've completed the free strings 100%, pulling to http://translate.marketpress.com/projects/plugins/backwpup-pro/pt/default and https://translate.wordpress.org/locale/pt/default/wp-plugins/backwpup in a minute.

I'll pull here the modified strings also.
Thanks for your support.

**Comment by danielhuesken** [comment]
I have now change the string in ouer development so that sy came with the next update.

We have to say thanls for your work.

**Comment by pedro-mendonca** [comment]
You're welcome :+1: 
I think your plugin is so good that it's worth all the effort to translate a thousand strings :)
For the Pro version I can't understand the context of some of them, maybe in a near future! :)

**Comment by pedro-mendonca** [comment]
Hi again @danielhuesken,
I'm positive that this might not be the correct place to question you about some strings translation, but as we've already disscussed some before, I'll write it againg here just too keep it all in one place.

I'm trying to complete the rest of the Pro strings, but as I don't have it it's a difficult to check the strings context. Still, I've tryied to complete it all. I have some doubts in two last strings that I must ask you about it's meaning, as they look a bit ambigous.

`Dump database create view "%s"`
`Number of files to keep in folder. (Archives deleted before 3 months after they have been stored may cause extra costs when deleted.)`

Can you please explain it a bit so that I can translate it without any errors?

**Comment by danielhuesken** [comment]
Hi, we currentli working on making some texts better to understand. If we are ready i will push it to wordpress.org dev version.

**Pull request merged**
